# kt/props/tb/common.properties
imageServer:
  host: /link/attachfile_manager/image
yamlServer:
  host: /link/attachfile_manager/yaml
yaml:
  file:
    path: /link/attachfile_manager/yaml
typeServer:
  host: /link/attachfile_manager/fileType
apidocServer:
  host: /link/attachfile_manager/apidoc
wsdlServer:
  host: /link/attachfile_manager/wsdl
  new:
    host: /link/attachfile_manager/wsdl/new
upload:
  output:
    path: /link/attachfile_manager/apidoc/yamlDoc
  image:
    path: /upload
  file:
    path: /upload
  path:
    request: /upload/request
    master: /upload/master
is:
  local: true
server:
  url: http://localhost:80
search:
  pageSize: 20
editor:
  tomcat:
    use: true
  tomcathost:
    url: /apieditor/
  host:
    url: http://10.214.188.60:8080/#/?
  defult:
    host: openapis.kt.com
mypage:
  fileNm: authority.docx
wsdlImport:
  js:
    fileNm: wsdlImport.js
  yaml:
    fileNm: service.yaml
apidocImport:
  json:
    fileNm: swagger.json
apiImport:
  loop:
    cnt: 2
  sleep:
    cnt: 3000
psso:
  logout:
    url: ""
  api:
    login:
      method: "##iframe"
      errorUrl: https://psso.show.co.kr/PSSO_WEB/LoginReturnCode.asp
      clientkey: ""
      siteUrl: apimanager.kt.co.kr
      checkurl: http://172.31.31.32:8080/PSSO_API/DefaultLogin.asp
      status:
        success: "11"
        fail: "12"
    sms:
      checkurl: https://psso.show.co.kr/PSSO_API/SMSCertSend.asp
  reset:
    pw: ${PSSO_RESET_PW}
  aes:
    key: ${PSSO_AES_KEY}
mail:
  receiver:
    apilink: apilink@kt.com
apiLink:
  host:
    url: https://apilink.kt.co.kr/rest/procsendMail
apilink:
  mail:
    key: ${APILINK_MAIL_KEY}
  onm:
    site: http://172.31.55.90:8088
  user:
    terms:
      form:
        link: http://tb.apilink.kt.co.kr/login/user/termsForm.do
    find:
      user:
        id:
          link: http://tb.apilink.kt.co.kr/login/findUserId.do
        pw:
          link: http://tb.apilink.kt.co.kr/login/findUserPw.do
  cus:
    in:
      auth:
        test:
          url: https://cus-in.tbapi.kt.com/AuthTest
  msg:
    in:
      auth:
        test:
          url: https://msg-in.tbapi.kt.com/AuthTest
  find:
    user:
      id:
        link: http://tb.apilink.kt.co.kr/login/findUserId.do
      pw:
        link: http://tb.apilink.kt.co.kr/login/findUserPw.do
apisystem:
  apidel:
    authid: ${APISYSTEM_APIDEL_AUTHID}
  observer:
    autid: "72"
    autnm: GateWay 운영자
    bstmng:
      userlist: ${APISYSTEM_OBSERVER_BSTMNG_USERLIST}
    bstviewer:
      userlist: ${APISYSTEM_OBSERVER_BSTVIEWER_USERLIST}
  sysid:
    arsenal: ARSENAL
    biznaru: BIZNARU
security:
  verify:
    mail: N
deployapply:
  mail:
    list: ${DEPLOYAPPLY_MAIL_LIST}
shub:
  api:
    instauth:
      tb:
        url: http://172.31.30.14:8080/instauth
      prd:
        url: https://172.31.171.14/instauth
  authorization:
    key: ${REST_AUTHORIZATION}
  2fa:
    verifysend:
      url: ${SHUB_2FA_VERIFYSEND_URL:https://msg-in.tbapi.kt.com/verify/v1.0/verify_send}
    verifycheck:
      url: ${SHUB_2FA_VERIFYCHECK_URL:https://msg-in.tbapi.kt.com/verify/v1.0/verify_check}
rest:
  authorization: ${REST_AUTHORIZATION}
new:
  psso:
    api:
      clientkey: ${NEW_PSSO_API_CLIENTKEY}
      member:
        join: https://int-in.tbapi.kt.com/psso/v2.0/psso_defaultJoin
        idcheck: https://int-in.tbapi.kt.com/psso/v2.0/psso_memberIdCheck
        logincheck: ${PSSO_MEMBER_LOGINCHECK_URL:https://int-in.tbapi.kt.com/psso/v2.0/psso_memberLogin}
        passwordchange: https://int-in.tbapi.kt.com/psso/v2.0/psso_pwdChangeAgainReset
        certcheck: https://int-in.tbapi.kt.com/psso/v2.0/psso_certCheck
        joininfo: https://int-in.tbapi.kt.com/psso/v2.0/psso_userInfoByUserName
        findmember: https://int-in.tbapi.kt.com/psso/v2.0/psso_existByIdPlus
        memberinfoupdate: https://int-in.tbapi.kt.com/psso/v2.0/psso_userInfoUpdate
        memberinfosearch: https://int-in.tbapi.kt.com/psso/v2.0/psso_userInfoSearch
  login:
    mode: Y
apimeneger:
  log:
    filepath: /var/log/LAMP/
    service:
      name: OG081704
      domain: http://tb.apimanager.kt.co.kr
  logcenter:
    channel: AII7120006864QJFCHL
logcenter:
  record:
    mode: Y
gitlab:
  arsenal:
    host: http://gitlab.msa.kt.com/
    base:
      path: /tree/master/devops/swagger/
    token: ""
  private:
    token: ""
